# Generated by Django 2.2.1 on 2019-11-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('direction', models.CharField(blank=True, choices=[('h', 'html'), ('j', 'js'), ('p', 'php'), ('py', 'python')], default='py', help_text='Направление курса', max_length=1)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_start_registration', models.DateField(blank=True, null=True, verbose_name='Начало регистрации')),
                ('level', models.CharField(blank=True, choices=[('j', 'Junior'), ('m', 'Middle'), ('s', 'Senior'), ('l', 'Lead')], default='j', help_text='Уровень курса', max_length=1)),
            ],
        ),
    ]
