# Generated by Django 2.2.1 on 2019-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('direction', models.CharField(blank=True, choices=[('html5', 'html'), ('javascript', 'js'), ('php', 'php'), ('python', 'python')], default='py', help_text='Направление курса', max_length=200)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_start_registration', models.DateField(blank=True, null=True, verbose_name='Начало регистрации')),
                ('level', models.CharField(blank=True, choices=[('Начинающий', 'Junior'), ('Средний', 'Middle'), ('Увереный', 'Senior'), ('Опытный', 'Lead')], default='j', help_text='Уровень курса', max_length=200)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(help_text='Описание курса', max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(to='api.Course'),
        ),
    ]
