# Generated by Django 2.2.1 on 2019-11-13 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(help_text='Описание курса', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CourseParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Courses')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
