# Generated by Django 2.2.1 on 2019-11-14 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191113_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('direction', models.CharField(blank=True, choices=[('h', 'html'), ('j', 'js'), ('p', 'php'), ('py', 'python')], default='py', help_text='Направление курса', max_length=1)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_start_registration', models.DateField(blank=True, null=True, verbose_name='Начало регистрации')),
                ('level', models.CharField(blank=True, choices=[('j', 'Junior'), ('m', 'Middle'), ('s', 'Senior'), ('l', 'Lead')], default='j', help_text='Уровень курса', max_length=1)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(help_text='Описание курса', max_length=2000, null=True)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='courseparticipants',
            name='id_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Course'),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
