# Generated by Django 2.2.1 on 2019-11-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
