# Generated by Django 2.2.1 on 2019-11-14 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191114_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.CharField(blank=True, choices=[('h', 'html'), ('j', 'js'), ('p', 'php'), ('py', 'python')], default='py', help_text='Направление курса', max_length=2),
        ),
        migrations.RemoveField(
            model_name='course',
            name='members',
        ),
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
