# Generated by Django 2.2.1 on 2019-11-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191114_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseParticipants',
        ),
    ]
