# Generated by Django 2.2.1 on 2019-11-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191114_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='members',
        ),
    ]
