# Generated by Django 2.2.1 on 2019-11-14 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_course_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='in_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
