# Generated by Django 2.2.1 on 2019-11-14 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191114_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='leaders', to=settings.AUTH_USER_MODEL),
        ),
    ]
