# Generated by Django 2.2.1 on 2019-11-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_course_leaders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='leaders',
        ),
        migrations.RemoveField(
            model_name='course',
            name='members',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='in_courses', to='api.Course'),
        ),
    ]
